changelogFile=changelog/db.changelog-master.yaml
url=jdbc:sqlserver://localhost:1433;databaseName=portfolio;encrypt=false;trustServerCertificate=true
username=sa
password=PortfolioDev1!
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
